version = 1

[[annotations]]
path = [
    "README.md",
    "docs/.bundle/config",
    "docs/Gemfile.lock",
    "docs/*.md",
    "quay.io-travier-fedora-sysexts.pub",
]
SPDX-FileCopyrightText = [
    "Timothée Ravier <tim@siosm.fr>"
]
SPDX-License-Identifier = "CC0-1.0"
