# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

export JEKYLL_ENV:="production"

serve:
  bundle exec jekyll serve --strict_front_matter --config _config.yml,_config_local.yml
